import madhubani from "@/assets/art-madhubani.jpg";
import pattachitra from "@/assets/art-pattachitra.jpg";
import warli from "@/assets/art-warli.jpg";
import dhokra from "@/assets/art-dhokra.jpg";
import bluePottery from "@/assets/art-bluepottery.jpg";
import banarasi from "@/assets/art-banarasi.jpg";
import cheriyal from "@/assets/art-cheriyal.jpg";

import type { ArtForm } from "./types";

export const images = {
  madhubani,
  pattachitra,
  warli,
  dhokra,
  bluePottery,
  banarasi,
  cheriyal,
};

export const artForms: ArtForm[] = [
  {
    id: "cheriyal",
    name: "Cheriyal Scroll Painting",
    category: "Painting",
    stateId: "telangana",
    state: "Telangana",
    district: "Cheriyal, Siddipet",
    status: "critically-endangered",
    statusFactors: [
      "Practised today by a small number of families in and around Cheriyal.",
      "Few younger practitioners are taking up the full scroll tradition.",
      "The itinerant storyteller communities the scrolls were painted for have largely moved to other work.",
      "Much of the knowledge — pigment preparation, narrative order — is held orally rather than written down.",
      "Limited digital visibility outside craft fairs and a handful of museums.",
    ],
    summary:
      "A narrative scroll tradition of the Nakashi painter families of Telangana: long khadi panels painted in registers, unrolled scene by scene while a story is sung aloud.",
    origin:
      "Cheriyal town, Siddipet district, Telangana — with painter families historically working across the surrounding Telangana countryside.",
    history: [
      "Cheriyal scrolls belong to a wider Deccan tradition of painted storytelling. The scrolls were not made as pictures to hang; they were props. A caste of travelling narrators carried them from village to village, unrolling one panel at a time as they sang episodes from epics and community genealogies.",
      "The painters — Nakashi families — worked to commission for particular narrator communities, and each scroll's sequence of scenes was fixed by the story it accompanied. A single scroll could run several metres and take months.",
      "As cinema, radio and later television replaced the travelling performance, demand for full scrolls fell away. Painters adapted, working on smaller single panels, masks and figures made for collectors rather than performers.",
    ],
    timeline: [
      { period: "Pre-modern Deccan", note: "Painted scrolls made for itinerant narrator communities across the Telangana region." },
      { period: "20th century", note: "Demand declines as recorded and broadcast entertainment replaces village storytelling performance." },
      { period: "Later 20th century", note: "Painters shift to single panels, masks and smaller works for exhibitions and collectors." },
      { period: "Today", note: "Practised by a small number of families; taught mainly within households and occasional workshops." },
    ],
    materials: [
      "Khadi cotton cloth",
      "Rice starch and tamarind seed paste",
      "White clay (suddha matti) ground coat",
      "Natural pigments — lamp black, ochre, indigo, white from seashell",
      "Gum from the tree resin as binder",
      "Squirrel-hair and goat-hair brushes",
    ],
    techniques: [
      { title: "Preparing the cloth", detail: "Khadi is soaked, dried and coated several times with a paste of rice starch, tamarind seed and white clay, then sun-dried and burnished until the surface takes a line cleanly." },
      { title: "Laying out the registers", detail: "The scroll is divided into horizontal panels. Each panel holds one episode, read from the top down in the order the narrator will sing them." },
      { title: "Drawing the outline", detail: "Figures are sketched freehand in a light earth tone — profile faces, large eyes, gesture carried by hands rather than expression." },
      { title: "Filling the ground", detail: "A saturated red field is laid behind the figures. The red is the signature of the tradition and separates one panel from the next." },
      { title: "Colouring the figures", detail: "Skin in yellow ochre, deities in blue, borders in white and ochre, applied flat with no shading." },
      { title: "Final black line", detail: "Every form is redrawn in lamp black at the end. This last line is what makes the figures readable from a distance in lamplight." },
    ],
    significance: [
      "The scroll is an instrument of performance, not a decoration — its composition follows the order in which a story is sung.",
      "Panels often carried community genealogies, so a scroll doubled as a record of who a village believed itself to be.",
      "The flat red ground, profile faces and continuous black outline are a regional visual language distinct from other Indian narrative painting.",
    ],
    image: cheriyal,
    gallery: [cheriyal, pattachitra, madhubani],
    artisanIds: ["vanaja-nakash"],
    relatedFormIds: ["kalamkari", "patua-scroll", "pattachitra"],
    sources: [
      "Artisan interviews recorded by Kalakhata (prototype documentation).",
      "Regional craft documentation and museum collection notes.",
    ],
    documentedArtisans: 9,
  },
  {
    id: "madhubani",
    name: "Madhubani Painting",
    category: "Painting",
    stateId: "bihar",
    state: "Bihar",
    district: "Madhubani",
    status: "at-risk",
    statusFactors: [
      "Widely known, but a large share of what sells is machine-printed imitation.",
      "Natural pigment preparation is practised by fewer households each generation.",
      "Artists depend on intermediaries who capture much of the final price.",
    ],
    summary:
      "Wall and floor painting by the women of the Mithila region, made for weddings and festivals, now also worked on handmade paper and cloth.",
    origin: "Jitwarpur and surrounding villages, Madhubani district, Bihar.",
    history: [
      "Madhubani began on the replastered mud walls of Mithila homes — painted for weddings, births and festivals, and washed away with the next monsoon.",
      "From the second half of the twentieth century the same imagery moved onto paper, which allowed it to travel and be sold, and turned a domestic ritual practice into a livelihood.",
    ],
    timeline: [
      { period: "Traditional practice", note: "Painted directly on the walls and floors of homes for ritual occasions." },
      { period: "Mid-20th century", note: "Transfer of the tradition onto handmade paper opens a market beyond the village." },
      { period: "Today", note: "Practised widely across Mithila; natural-pigment work is the smaller share." },
    ],
    materials: ["Handmade paper and cotton cloth", "Soot black", "Turmeric yellow", "Kusum flower red", "Bamboo twig and cotton nibs"],
    techniques: [
      { title: "Kachni line work", detail: "Fine hatched line drawing that fills a form with texture rather than colour." },
      { title: "Bharni fill", detail: "Solid colour blocks bounded by a heavy outline." },
      { title: "No empty ground", detail: "Every remaining space is filled with flowers, fish, birds or geometric fill." },
    ],
    significance: [
      "The kohbar panel painted for a wedding chamber is a marriage document as much as an artwork.",
      "The tradition is carried almost entirely by women and passed from mother to daughter.",
    ],
    image: madhubani,
    gallery: [madhubani, pattachitra],
    artisanIds: ["sunaina-devi"],
    relatedFormIds: ["patua-scroll", "gond", "cheriyal"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 42,
  },
  {
    id: "pattachitra",
    name: "Pattachitra",
    category: "Painting",
    stateId: "odisha",
    state: "Odisha",
    district: "Puri (Raghurajpur)",
    status: "at-risk",
    statusFactors: [
      "Concentrated in a small number of villages.",
      "Cloth preparation takes days and is increasingly skipped in cheaper work.",
      "Younger practitioners often move to faster, smaller souvenir formats.",
    ],
    summary:
      "Temple painting on prepared cloth, bound to the Jagannath calendar of Puri and worked in natural stone colours.",
    origin: "Raghurajpur and Dandasahi, Puri district, Odisha.",
    history: [
      "Pattachitra developed in the service of the Jagannath temple, where painted cloth substitutes for the deities during periods when the images are not on view.",
      "Raghurajpur remains a village of painters where nearly every household works the tradition and the walls themselves are painted.",
    ],
    timeline: [
      { period: "Temple tradition", note: "Painting practised as a ritual service tied to the Jagannath calendar." },
      { period: "Modern period", note: "Work opens to collectors; palm-leaf etching becomes a parallel livelihood." },
      { period: "Today", note: "Practised village-wide, with wide variation in preparation quality." },
    ],
    materials: ["Layered cotton cloth", "Tamarind seed paste", "Natural stone and shell colours", "Fine animal-hair brushes", "Palm leaf"],
    techniques: [
      { title: "Preparing the patta", detail: "Old cotton sarees are glued in layers with tamarind seed paste and dried for days." },
      { title: "Burnishing", detail: "The dried sheet is polished with a river stone until it takes a brush like paper." },
      { title: "Border first", detail: "The decorative border is painted before the central scene, framing the composition from the outside in." },
    ],
    significance: [
      "The painting is a ritual substitute, not only an image — its use is fixed by the temple calendar.",
      "Palm-leaf etching preserves a manuscript technique alongside the painting tradition.",
    ],
    image: pattachitra,
    gallery: [pattachitra, cheriyal],
    artisanIds: ["raghunath-maharana"],
    relatedFormIds: ["cheriyal", "patua-scroll", "madhubani"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 28,
  },
  {
    id: "warli",
    name: "Warli Painting",
    category: "Painting",
    stateId: "maharashtra",
    state: "Maharashtra",
    district: "Palghar (Ganjad)",
    status: "at-risk",
    statusFactors: [
      "The wall-painting context — ritual occasions in the home — is shrinking.",
      "The motifs are heavily copied commercially without the community seeing returns.",
      "Rice-paste and cow-dung ground work is being replaced by acrylic on canvas.",
    ],
    summary:
      "Ritual wall painting of the Warli community: circles, triangles and lines in rice paste on an earth-red ground.",
    origin: "Ganjad and surrounding villages, Palghar district, Maharashtra.",
    history: [
      "Warli painting was made on the mud walls of a home for weddings and harvest, by women, and was never intended to last beyond a season.",
      "It entered the wider art world in the twentieth century through individual painters who transferred the vocabulary to paper and canvas.",
    ],
    timeline: [
      { period: "Ritual practice", note: "Painted on interior mud walls for weddings and seasonal rites." },
      { period: "20th century", note: "Transfer to paper and canvas brings the tradition to a national audience." },
      { period: "Today", note: "Widely reproduced commercially; community practice is narrower than its visibility suggests." },
    ],
    materials: ["Mud and cow-dung wall wash", "Rice paste white", "Bamboo stick brushes", "Cotton canvas and handmade paper"],
    techniques: [
      { title: "Three shapes", detail: "Circle, triangle and line carry the entire vocabulary — sun, mountain and human body." },
      { title: "The tarpa spiral", detail: "Dancers are drawn in an unbroken spiral around the musician, with no beginning or end." },
      { title: "Chewed bamboo brush", detail: "The stick is chewed at one end until it splays into a brush." },
    ],
    significance: [
      "The painting records the agricultural year and the community's relationship to it.",
      "Its impermanence was part of its meaning: it was renewed, not preserved.",
    ],
    image: warli,
    gallery: [warli],
    artisanIds: ["jivya-more"],
    relatedFormIds: ["gond", "madhubani"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 31,
  },
  {
    id: "dhokra",
    name: "Dhokra Metal Casting",
    category: "Metal",
    stateId: "chhattisgarh",
    state: "Chhattisgarh",
    district: "Bastar",
    status: "endangered",
    statusFactors: [
      "Firing is fuel-intensive and increasingly expensive for family workshops.",
      "Each mould is destroyed in casting, so output is slow and cannot be scaled.",
      "Cheap cast imitations undercut hand-worked pieces.",
      "Younger family members frequently migrate for wage work.",
    ],
    summary:
      "Lost-wax bell-metal casting practised in Bastar, in which a clay mould must be broken to release each figure.",
    origin: "Bastar district, Chhattisgarh, with related traditions across eastern India.",
    history: [
      "Lost-wax casting is one of the oldest continuously practised metal techniques in the subcontinent.",
      "In Bastar it produced ritual figures, measuring bowls, lamps and animal forms for local use long before it produced collectables.",
    ],
    timeline: [
      { period: "Ancient technique", note: "Lost-wax casting practised in the subcontinent since antiquity." },
      { period: "Village economy", note: "Figures, lamps and measures cast for household and ritual use." },
      { period: "Today", note: "Family furnaces fire on a weekly cycle; output limited by fuel and labour." },
    ],
    materials: ["Beeswax and resin threads", "River clay", "Bell metal (brass alloy)", "Charcoal and dung cake fuel"],
    techniques: [
      { title: "Clay core", detail: "A rough clay core is shaped and dried in the sun." },
      { title: "Wax threading", detail: "Fine wax threads are coiled by hand over the core — this coiling is the surface you see in the finished metal." },
      { title: "Investment and firing", detail: "The model is packed in clay, fired so the wax runs out, and molten metal poured into the void." },
      { title: "Breaking the mould", detail: "The clay is shattered to free the figure. No two pieces can be identical." },
    ],
    significance: [
      "Every piece is unique by necessity — the mould cannot survive its own casting.",
      "The forms still in production carry Bastar's ritual and everyday iconography.",
    ],
    image: dhokra,
    gallery: [dhokra],
    artisanIds: ["budhiyarin-bai"],
    relatedFormIds: ["channapatna", "bidri"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 17,
  },
  {
    id: "blue-pottery",
    name: "Jaipur Blue Pottery",
    category: "Pottery",
    stateId: "rajasthan",
    state: "Rajasthan",
    district: "Jaipur",
    status: "at-risk",
    statusFactors: [
      "A high share of every firing cracks, making the craft financially fragile.",
      "Hand-ground cobalt is being replaced by cheaper industrial substitutes.",
      "Workshops face pressure from mass-produced lookalike ceramics.",
    ],
    summary:
      "A quartz-bodied glazed ware containing no clay, painted in cobalt blue and fired at low temperature.",
    origin: "Jaipur, Rajasthan — technique carried from Persia through Kashmir.",
    history: [
      "The technique travelled with Persian and Central Asian craft into north India and settled in Jaipur under court patronage.",
      "Its body is unusual: powdered quartz, glass, borax and gum, pressed into plaster moulds rather than thrown on a wheel.",
    ],
    timeline: [
      { period: "Arrival", note: "Persian-derived glazed ware technique reaches north India." },
      { period: "Court period", note: "Jaipur workshops refine the quartz body and cobalt palette." },
      { period: "Today", note: "A small number of workshops still mix and grind their own colours." },
    ],
    materials: ["Powdered quartz", "Glass frit and borax", "Gum and fuller's earth", "Cobalt oxide", "Plaster moulds"],
    techniques: [
      { title: "Mixing the body", detail: "No clay is used; quartz, glass, borax and gum are worked into a dough." },
      { title: "Moulding", detail: "The body is pressed into plaster moulds and dried slowly to avoid cracking." },
      { title: "Painting and glazing", detail: "Cobalt patterns are painted directly on the raw body and covered with a glass glaze before a single low firing." },
    ],
    significance: [
      "One of the few Indian ceramic traditions with a non-clay body.",
      "The cobalt-and-white palette is a direct visual link to Persian glazed ware.",
    ],
    image: bluePottery,
    gallery: [bluePottery],
    artisanIds: ["iqbal-khan"],
    relatedFormIds: ["kalamkari", "banarasi"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 23,
  },
  {
    id: "banarasi",
    name: "Banarasi Handloom Weaving",
    category: "Textiles",
    stateId: "uttar-pradesh",
    state: "Uttar Pradesh",
    district: "Varanasi",
    status: "endangered",
    statusFactors: [
      "Powerlooms reproduce handloom designs in a fraction of the time.",
      "Real zari is costly and often substituted.",
      "Weavers' children are moving out of the trade in large numbers.",
      "A kadhwa saree can take months, which few buyers price correctly.",
    ],
    summary:
      "Pit-loom brocade weaving of Varanasi, in which the pattern is held in knotted jala threads above the loom and read like a score.",
    origin: "Madanpura, Alaipura and surrounding lanes of Varanasi, Uttar Pradesh.",
    history: [
      "Varanasi's brocade weaving grew around court and temple demand for figured silk with metal thread.",
      "The jala system — a pattern held in cords above the loom — allowed complex repeats long before mechanical jacquards arrived.",
    ],
    timeline: [
      { period: "Court and temple demand", note: "Figured silk with gold and silver thread woven for ceremonial use." },
      { period: "Jala loom", note: "Pattern cords above the loom allow complex repeats to be woven by hand." },
      { period: "Today", note: "Handloom weavers compete directly with powerloom reproductions of their own designs." },
    ],
    materials: ["Mulberry silk", "Real zari (gold or silver wrapped thread)", "Pit loom with jala pattern cords"],
    techniques: [
      { title: "Reading the jala", detail: "The design is knotted into cords above the loom; a second person lifts the sequence as the weaver throws the shuttle." },
      { title: "Kadhwa weaving", detail: "Each motif is woven separately rather than carried across the back — slower, but the reverse stays clean." },
      { title: "Zari work", detail: "Metal-wrapped thread is introduced by hand on every pick that requires it." },
    ],
    significance: [
      "A single kadhwa saree can hold months of continuous work and cannot be unpicked.",
      "The lanes of Varanasi function as a single distributed workshop across many households.",
    ],
    image: banarasi,
    gallery: [banarasi],
    artisanIds: ["shahid-ansari"],
    relatedFormIds: ["muga-silk", "kalamkari"],
    sources: ["Artisan interviews recorded by Kalakhata (prototype documentation)."],
    documentedArtisans: 56,
  },
  {
    id: "kalamkari",
    name: "Kalamkari",
    category: "Textiles",
    stateId: "telangana",
    state: "Andhra Pradesh & Telangana",
    district: "Srikalahasti / Pedana",
    status: "at-risk",
    statusFactors: [
      "The hand-drawn pen tradition is far smaller than the block-printed one sold under the same name.",
      "Natural dye preparation takes weeks and is often replaced with chemical dye.",
    ],
    summary:
      "Cloth drawn with a bamboo pen in fermented iron liquor and dyed with madder and myrobalan, narrating temple stories.",
    origin: "Srikalahasti (pen work) and Pedana (block work), Andhra Pradesh.",
    history: [
      "Kalamkari developed as temple cloth — painted hangings narrating episodes from epics, made to be displayed during festivals.",
      "The pen tradition of Srikalahasti and the block tradition of Pedana are distinct crafts sharing a name and a dye chemistry.",
    ],
    timeline: [
      { period: "Temple cloth", note: "Painted narrative hangings made for festival display." },
      { period: "Trade period", note: "Dyed cottons from the Coromandel coast become a major export textile." },
      { period: "Today", note: "Hand-drawn pen work is the smaller and more fragile of the two branches." },
    ],
    materials: ["Cotton cloth treated with myrobalan", "Fermented iron liquor (black)", "Madder root (red)", "Indigo", "Bamboo kalam pen"],
    techniques: [
      { title: "Myrobalan treatment", detail: "The cloth is soaked in myrobalan and buffalo milk so the dye takes and the black stays sharp." },
      { title: "Drawing with the kalam", detail: "A bamboo pen bound with cloth holds the iron liquor and releases it under finger pressure." },
      { title: "Repeated washing", detail: "The cloth is washed in running water between every dye stage — the reason the colours stay clear." },
    ],
    significance: [
      "One of the few surviving traditions where an entire narrative is drawn freehand on cloth.",
      "Its dye chemistry is a direct link to India's historic textile trade.",
    ],
    image: pattachitra,
    gallery: [pattachitra, cheriyal],
    artisanIds: [],
    relatedFormIds: ["cheriyal", "banarasi"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 34,
  },
  {
    id: "gond",
    name: "Gond Painting",
    category: "Painting",
    stateId: "madhya-pradesh",
    state: "Madhya Pradesh",
    district: "Dindori / Mandla",
    status: "at-risk",
    statusFactors: [
      "The forest knowledge the imagery draws on is thinning with changing land use.",
      "Widely imitated by non-community painters.",
    ],
    summary:
      "Forest cosmology drawn in fields of dots and dashes — trees, animals and spirits built from repeated marks.",
    origin: "Gond community villages of Dindori and Mandla, Madhya Pradesh.",
    history: [
      "Gond painting moved from house walls and floors onto paper and canvas in the later twentieth century.",
      "Each painter develops a personal signature fill — dots, commas, fish-scales — which identifies their work.",
    ],
    timeline: [
      { period: "Wall practice", note: "Painted on the walls and floors of homes as seasonal decoration." },
      { period: "Late 20th century", note: "Transfer to paper brings individual painters into national exhibitions." },
      { period: "Today", note: "Practised by a growing but commercially pressured group of painters." },
    ],
    materials: ["Handmade paper and canvas", "Earth and plant colour, now often acrylic", "Fine brushes"],
    techniques: [
      { title: "Outline first", detail: "The animal or tree is drawn as a continuous outline before any fill." },
      { title: "Signature fill", detail: "The interior is filled with one repeated mark, unique to the painter." },
    ],
    significance: ["The imagery records a relationship with forest, animal and ancestor that is specific to the community."],
    image: warli,
    gallery: [warli, madhubani],
    artisanIds: [],
    relatedFormIds: ["warli", "madhubani"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 26,
  },
  {
    id: "patua-scroll",
    name: "Patua Scroll Painting",
    category: "Painting",
    stateId: "west-bengal",
    state: "West Bengal",
    district: "Pingla, Paschim Medinipur",
    status: "endangered",
    statusFactors: [
      "The painters are also the singers — losing the song loses half the craft.",
      "Few younger patuas learn the full sung repertoire.",
      "Scroll performance has little remaining commercial context outside fairs.",
    ],
    summary:
      "Long vertical scrolls unrolled while the painter sings the story painted on them.",
    origin: "Naya village, Pingla, Paschim Medinipur, West Bengal.",
    history: [
      "Patuas paint and perform: the scroll is unrolled panel by panel as the painter sings the accompanying pater gaan.",
      "The repertoire has always absorbed current events alongside mythological subjects.",
    ],
    timeline: [
      { period: "Village performance", note: "Scrolls carried from village to village and sung for a small payment." },
      { period: "Today", note: "Performance survives mainly through fairs, festivals and documentation projects." },
    ],
    materials: ["Paper backed with cloth", "Plant and mineral colour", "Bamboo rollers"],
    techniques: [
      { title: "Panel sequence", detail: "Scenes are painted in the order the song moves, top to bottom." },
      { title: "Song and paint together", detail: "The painter composes the sung verse alongside the image." },
    ],
    significance: ["One of the few living traditions where the same person is painter, composer and performer."],
    image: pattachitra,
    gallery: [pattachitra],
    artisanIds: [],
    relatedFormIds: ["cheriyal", "pattachitra"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 14,
  },
  {
    id: "muga-silk",
    name: "Muga Silk Weaving",
    category: "Textiles",
    stateId: "assam",
    state: "Assam",
    district: "Sualkuchi",
    status: "at-risk",
    statusFactors: [
      "Muga silkworm rearing depends on specific host trees and a narrow climate band.",
      "Yarn supply is unpredictable, which pushes weavers toward other fibres.",
    ],
    summary:
      "Golden silk reared in Assam and woven on handlooms in Sualkuchi, unusual for its natural sheen and durability.",
    origin: "Sualkuchi and the Brahmaputra valley, Assam.",
    history: [
      "Muga silk is reared nowhere else at scale; the colour is natural rather than dyed.",
      "Sualkuchi functions as a weaving town where a large share of households run looms.",
    ],
    timeline: [
      { period: "Traditional rearing", note: "Muga reared on som and soalu trees in the Brahmaputra valley." },
      { period: "Today", note: "Rearing is climate-sensitive and yarn supply fluctuates year to year." },
    ],
    materials: ["Muga silk yarn", "Throw-shuttle and fly-shuttle handlooms"],
    techniques: [
      { title: "Rearing", detail: "Silkworms are reared outdoors on host trees rather than indoors." },
      { title: "Weaving the mekhela", detail: "Motifs are woven in rather than printed, often in contrasting silk." },
    ],
    significance: ["The golden colour is intrinsic to the fibre and cannot be replicated by dyeing."],
    image: banarasi,
    gallery: [banarasi],
    artisanIds: [],
    relatedFormIds: ["banarasi"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 38,
  },
  {
    id: "tanjore",
    name: "Tanjore Painting",
    category: "Painting",
    stateId: "tamil-nadu",
    state: "Tamil Nadu",
    district: "Thanjavur",
    status: "thriving",
    statusFactors: [
      "Steady devotional demand keeps workshops occupied.",
      "Gold foil and gesso technique is actively taught in the region.",
    ],
    summary:
      "Devotional panel painting built up in gesso relief and surfaced with gold foil and set stones.",
    origin: "Thanjavur, Tamil Nadu.",
    history: [
      "Tanjore painting developed under court and temple patronage in the Thanjavur region as a devotional panel form.",
      "Its raised gesso work and gold foil give the surface a physical depth unusual in Indian painting.",
    ],
    timeline: [
      { period: "Court period", note: "Devotional panels made under Thanjavur patronage." },
      { period: "Today", note: "Actively practised and taught, with steady household demand." },
    ],
    materials: ["Seasoned wood plank", "Cloth and chalk gesso", "22k gold foil", "Semi-precious stones", "Natural and modern pigments"],
    techniques: [
      { title: "Gesso relief", detail: "Chalk paste is built up to raise crowns, jewellery and architecture off the panel." },
      { title: "Gold foil", detail: "Foil is laid over the raised areas and burnished." },
    ],
    significance: ["A rare Indian painting tradition worked in physical relief rather than flat colour."],
    image: madhubani,
    gallery: [madhubani],
    artisanIds: [],
    relatedFormIds: ["kerala-mural"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 61,
  },
  {
    id: "kerala-mural",
    name: "Kerala Mural Painting",
    category: "Painting",
    stateId: "kerala",
    state: "Kerala",
    district: "Thrissur / Guruvayur",
    status: "at-risk",
    statusFactors: [
      "Wall commissions are limited and mostly tied to temple restoration.",
      "Vegetable-colour preparation is practised by a small number of painters.",
    ],
    summary:
      "Temple wall painting worked in five vegetable colours, with figures drawn in a strict iconographic grammar.",
    origin: "Temple walls across central Kerala.",
    history: [
      "Kerala murals were painted directly onto prepared temple walls using a limited five-colour palette.",
      "Training follows a fixed sequence: line, then form, then colour, then ornament.",
    ],
    timeline: [
      { period: "Temple wall tradition", note: "Murals painted on lime-prepared temple walls." },
      { period: "Today", note: "Sustained mainly through restoration work and formal mural schools." },
    ],
    materials: ["Lime-prepared wall surface", "Five vegetable and mineral colours", "Brushes of grass and animal hair"],
    techniques: [
      { title: "Wall preparation", detail: "Lime plaster is worked and smoothed over weeks before painting begins." },
      { title: "Five colours only", detail: "The palette is deliberately restricted; depth comes from line, not shading." },
    ],
    significance: ["The iconographic grammar links the painting directly to Kerala's temple ritual and performance traditions."],
    image: pattachitra,
    gallery: [pattachitra],
    artisanIds: [],
    relatedFormIds: ["tanjore"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 19,
  },
  {
    id: "channapatna",
    name: "Channapatna Lacquered Wood",
    category: "Wood",
    stateId: "karnataka",
    state: "Karnataka",
    district: "Channapatna, Ramanagara",
    status: "at-risk",
    statusFactors: [
      "Competing directly with mass-produced plastic toys.",
      "Ivory-wood supply and lac colour preparation are both under pressure.",
    ],
    summary:
      "Turned ivory-wood toys coloured with lac on the lathe, finished with a dry palm leaf.",
    origin: "Channapatna, Ramanagara district, Karnataka.",
    history: [
      "Channapatna's turning workshops produce toys and household objects coloured with vegetable-dyed lac.",
      "The lac is applied while the piece spins on the lathe, melting onto the surface with the friction.",
    ],
    timeline: [
      { period: "Workshop tradition", note: "Lathe-turned toys made for local and regional markets." },
      { period: "Today", note: "Workshops persist but face heavy competition from industrial toys." },
    ],
    materials: ["Ivory wood (hale mara)", "Vegetable-dyed lac", "Dry palm leaf for polishing"],
    techniques: [
      { title: "Turning", detail: "The form is turned on a lathe from seasoned ivory wood." },
      { title: "Lac colouring", detail: "A stick of coloured lac is pressed to the spinning piece; friction melts it onto the surface." },
      { title: "Palm-leaf polish", detail: "A dry palm leaf held against the spinning piece burnishes the lac to a shine." },
    ],
    significance: ["The colour is food-safe lac rather than paint, which is why the toys were made for children."],
    image: dhokra,
    gallery: [dhokra],
    artisanIds: [],
    relatedFormIds: ["dhokra", "bidri"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 44,
  },
  {
    id: "bidri",
    name: "Bidriware",
    category: "Metal",
    stateId: "karnataka",
    state: "Karnataka",
    district: "Bidar",
    status: "endangered",
    statusFactors: [
      "A small number of workshops remain in Bidar.",
      "The blackening process depends on soil from a specific historic site.",
      "Inlay work is slow and difficult to price competitively.",
    ],
    summary:
      "Blackened zinc alloy inlaid with silver wire, the black raised by a soil-and-salt treatment unique to Bidar.",
    origin: "Bidar, Karnataka.",
    history: [
      "Bidriware developed in the Deccan as a courtly metal craft combining a dark alloy ground with fine silver inlay.",
      "The final blackening uses soil taken from an old fort site, mixed with ammonium chloride.",
    ],
    timeline: [
      { period: "Deccan court craft", note: "Vessels and hookah bases made with silver inlay for court use." },
      { period: "Today", note: "Practised by a limited number of workshops in and around Bidar." },
    ],
    materials: ["Zinc-copper alloy", "Pure silver wire and sheet", "Soil from the Bidar fort site", "Ammonium chloride"],
    techniques: [
      { title: "Casting and engraving", detail: "The object is cast, smoothed and the design chiselled into the surface." },
      { title: "Silver inlay", detail: "Silver wire is hammered into the engraved channels and filed flush." },
      { title: "Blackening", detail: "A soil-and-salt paste turns the alloy permanently matt black while leaving the silver bright." },
    ],
    significance: ["The contrast of matt black and bright silver is produced chemically, not by paint or plating."],
    image: dhokra,
    gallery: [dhokra],
    artisanIds: [],
    relatedFormIds: ["dhokra", "channapatna"],
    sources: ["Regional craft documentation (prototype)."],
    documentedArtisans: 11,
  },
];
