import type { Artisan } from "./types";
import { images } from "./artForms";

export const artisans: Artisan[] = [
  {
    id: "vanaja-nakash",
    name: "Vanaja Nakash",
    artFormId: "cheriyal",
    craft: "Cheriyal Scroll Painting",
    stateId: "telangana",
    place: "Cheriyal, Siddipet, Telangana",
    generations: "4th generation",
    yearsPractising: 27,
    specialisation: "Full-length narrative scrolls and painted masks",
    verification: "demo-verified",
    image: images.cheriyal,
    quote: "A scroll is not a picture. It is a night of singing, rolled up.",
    story: [
      "Vanaja belongs to a Nakashi household — painters who worked for the storyteller communities that once carried scrolls from village to village and sang the panels aloud after dark.",
      "She learned the way everyone in the family learned: grinding clay for the ground coat as a child, then borders, then the red field, and only after years the faces. The last black line is still drawn by her father when the scroll matters.",
      "The narrators stopped coming decades ago. She paints single panels and masks now, and takes commissions for full scrolls two or three times a year — each one several months of work.",
      "Every scroll she finishes is photographed panel by panel before it leaves the house. It is the only record the family keeps.",
    ],
    workshop:
      "A two-room house in Cheriyal with the long scroll table under the window. Cloth is coated in the courtyard and dried on the roof; pigments are ground in the same stone bowls her grandmother used.",
    process: [
      "Khadi is soaked, coated with rice starch, tamarind paste and white clay, and burnished until it takes a line.",
      "The scroll is ruled into panels in the order the story is sung.",
      "Figures are drawn freehand, the red ground is laid in, then flat colour.",
      "Every form is redrawn in lamp black last, so it reads from across a courtyard.",
    ],
  },
  {
    id: "sunaina-devi",
    name: "Sunaina Devi",
    artFormId: "madhubani",
    craft: "Madhubani Painting",
    stateId: "bihar",
    place: "Jitwarpur, Bihar",
    generations: "6th generation",
    yearsPractising: 34,
    specialisation: "Kachni line work in natural pigment",
    verification: "demo-verified",
    image: images.madhubani,
    quote: "My grandmother painted the walls of our home before she ever painted paper.",
    story: [
      "In Jitwarpur the monsoon decides everything — when the mud walls are replastered, when the pigments are ground, when the women of the village sit together and begin to draw.",
      "Sunaina learned the kachni line work at seven, tracing over her grandmother's fish and peacocks with a bamboo twig wrapped in cotton. She still refuses synthetic colour: her black is soot, her yellow turmeric, her red the kusum flower.",
      "Every piece she sells funds a Saturday class where eleven girls from the village learn the same lines she once traced.",
    ],
    workshop:
      "The front room of a mud-plastered house in Jitwarpur, with pigment jars on the sill and paper weighted flat under bricks.",
    process: [
      "Handmade paper is sized and left flat under weight for a day.",
      "The composition is drawn in a light earth line, border first.",
      "Kachni hatching fills the forms; colour is mixed fresh each morning.",
      "No space is left empty — fish, birds and flowers close every gap.",
    ],
  },
  {
    id: "raghunath-maharana",
    name: "Raghunath Maharana",
    artFormId: "pattachitra",
    craft: "Pattachitra",
    stateId: "odisha",
    place: "Raghurajpur, Odisha",
    generations: "9th generation",
    yearsPractising: 41,
    specialisation: "Jagannath cycle on prepared tussar cloth",
    verification: "demo-verified",
    image: images.pattachitra,
    quote: "The cloth must be prepared for ten days before a single line is allowed.",
    story: [
      "Raghurajpur is a village of one street where every house is a studio and every wall is a canvas. Raghunath's family has painted the Jagannath cycle here for generations.",
      "He glues layers of old cotton saree with tamarind seed paste, polishes the sheet with a river stone, and only then opens his brushes — some made from a single mouse whisker.",
      "He has never sold through a gallery. He would rather you write to him.",
    ],
    workshop:
      "A painted verandah in Raghurajpur where cloth is layered and dried, with palm leaves stacked for etching work in the off season.",
    process: [
      "Old cotton sarees are glued in layers with tamarind seed paste and dried for days.",
      "The dried patta is burnished with a river stone until it takes a brush.",
      "The border is painted before the central scene.",
      "Stone colours are applied flat, then the outline is restated in black.",
    ],
  },
  {
    id: "jivya-more",
    name: "Jivya More",
    artFormId: "warli",
    craft: "Warli Painting",
    stateId: "maharashtra",
    place: "Ganjad, Maharashtra",
    generations: "4th generation",
    yearsPractising: 30,
    specialisation: "Tarpa dance spirals on cow-dung wash",
    verification: "demo-verified",
    image: images.warli,
    quote: "A circle, a triangle, a line. That is the whole world if you look long enough.",
    story: [
      "Warli painting was never made to be sold. It was made on the mud walls of a home for a wedding, and washed away the next season.",
      "Jivya paints on canvas now so the work can travel, but he keeps the rice-paste white and the geometry unbroken: sun, farmer, tarpa dancers spiralling with no beginning.",
      "He teaches at the village school on Wednesdays, unpaid.",
    ],
    workshop:
      "A shaded courtyard in Ganjad where canvas is washed with mud and cow dung and left in the sun before painting.",
    process: [
      "Canvas is coated with a mud and cow-dung wash to imitate a wall.",
      "Rice is ground into a paste for the white.",
      "A bamboo stick is chewed at one end until it splays into a brush.",
      "The composition is built outward from a single spiral or sun.",
    ],
  },
  {
    id: "budhiyarin-bai",
    name: "Budhiyarin Bai",
    artFormId: "dhokra",
    craft: "Dhokra Metal Casting",
    stateId: "chhattisgarh",
    place: "Bastar, Chhattisgarh",
    generations: "5th generation",
    yearsPractising: 36,
    specialisation: "Wax-thread figures and measuring bowls",
    verification: "demo-verified",
    image: images.dhokra,
    quote: "Every mould breaks. That is why no two pieces can ever be the same.",
    story: [
      "Dhokra is lost-wax casting: bell metal poured into a clay mould that must be shattered to free the figure inside.",
      "Budhiyarin's family works through the dry months in Bastar, coiling wax threads by hand into elephants, tribal riders and measuring bowls.",
      "The furnace is fired once a week. Everything cast that day is everything she will sell that month.",
    ],
    workshop:
      "An open yard in Bastar with a dug charcoal furnace, clay drying racks and a wax bench worked in the cool hours.",
    process: [
      "A clay core is shaped and sun-dried.",
      "Wax threads are coiled by hand over the core — this coiling is the finished surface.",
      "The model is packed in clay, fired until the wax runs out, and metal is poured in.",
      "The clay is broken away and the piece filed by hand.",
    ],
  },
  {
    id: "iqbal-khan",
    name: "Iqbal Khan",
    artFormId: "blue-pottery",
    craft: "Jaipur Blue Pottery",
    stateId: "rajasthan",
    place: "Jaipur, Rajasthan",
    generations: "3rd generation",
    yearsPractising: 22,
    specialisation: "Hand-ground cobalt on quartz body",
    verification: "demo-verified",
    image: images.bluePottery,
    quote: "There is no clay in my clay. Only quartz, glass and the patience to fail.",
    story: [
      "Jaipur blue pottery came from Persia through Kashmir and settled in the pink city. The body contains no clay at all — powdered quartz, borax, gum and water, pressed into plaster moulds.",
      "A large share of every firing cracks. Iqbal's father told him that was the tax the craft charges for its colour.",
      "He mixes his own cobalt oxide and refuses the copper-green shortcut most workshops use now.",
    ],
    workshop:
      "A Jaipur workshop with plaster moulds stacked to the ceiling, a colour-grinding table and one low-temperature kiln.",
    process: [
      "Quartz, glass frit, borax and gum are worked into a dough.",
      "The dough is pressed into plaster moulds and dried slowly.",
      "Cobalt patterns are painted onto the raw body.",
      "A glass glaze goes over the paint and the piece is fired once.",
    ],
  },
  {
    id: "shahid-ansari",
    name: "Shahid Ansari",
    artFormId: "banarasi",
    craft: "Banarasi Handloom Weaving",
    stateId: "uttar-pradesh",
    place: "Varanasi, Uttar Pradesh",
    generations: "7th generation",
    yearsPractising: 38,
    specialisation: "Kadhwa weaving on a jala pit loom",
    verification: "demo-verified",
    image: images.banarasi,
    quote: "Six months on one saree. The loom knows my hands better than my children do.",
    story: [
      "In the lanes behind Madanpura the sound of the pit loom starts before the first azaan and stops long after dark.",
      "Shahid works a jala loom — the pattern held in knotted threads above his head, read like a score. A single kadhwa saree can take six months and cannot be undone.",
      "Powerlooms copy his designs in an afternoon. Selling directly is the only reason he still weaves.",
    ],
    workshop:
      "A pit loom set into the floor of a room off a Varanasi lane, with the jala cords hanging above and silk wound on the wall.",
    process: [
      "The design is knotted into the jala cords above the loom.",
      "Silk is warped and dressed onto the pit loom.",
      "Each motif is woven separately in the kadhwa method.",
      "Zari is introduced by hand on every pick that needs it.",
    ],
  },
];
