import type { Product } from "./types";
import { images } from "./artForms";

export const products: Product[] = [
  {
    id: "cheriyal-ramayana-panel",
    name: "Ramayana Episode Panel",
    price: "₹12,500",
    priceValue: 12500,
    detail: "Khadi cloth · 18 × 30 in · natural pigment",
    artisanId: "vanaja-nakash",
    artFormId: "cheriyal",
    materials: ["Khadi cotton", "Rice starch and tamarind ground", "Lamp black, ochre, indigo"],
    timeRequired: "About 5 weeks",
    storyBehind:
      "A single episode lifted out of a full scroll — the panel a narrator would have stopped on for an entire evening. Vanaja paints these separately now because full scrolls are commissioned only two or three times a year.",
    image: images.cheriyal,
  },
  {
    id: "cheriyal-mask",
    name: "Painted Cheriyal Mask",
    price: "₹3,800",
    priceValue: 3800,
    detail: "Sawdust and tamarind paste · 10 in · hand-painted",
    artisanId: "vanaja-nakash",
    artFormId: "cheriyal",
    materials: ["Sawdust and tamarind seed paste", "White clay ground", "Natural pigment"],
    timeRequired: "About 9 days",
    storyBehind:
      "Masks were made for the same performance tradition as the scrolls — worn or held while the story was sung. The features follow the scroll grammar exactly: profile nose, wide eye, black final line.",
    image: images.cheriyal,
  },
  {
    id: "madhubani-fish-lotus",
    name: "Fish & Lotus Scroll",
    price: "₹6,400",
    priceValue: 6400,
    detail: "Handmade paper · 22 × 30 in · natural pigments",
    artisanId: "sunaina-devi",
    artFormId: "madhubani",
    materials: ["Handmade paper", "Soot black", "Turmeric", "Kusum flower red"],
    timeRequired: "About 3 weeks",
    storyBehind:
      "Fish are painted for fertility and good fortune in Mithila. Sunaina fills the water around them with kachni hatching so no part of the paper is left bare.",
    image: images.madhubani,
  },
  {
    id: "madhubani-kohbar",
    name: "Kohbar Wedding Panel",
    price: "₹14,800",
    priceValue: 14800,
    detail: "Cotton canvas · 36 × 48 in · 40 days of work",
    artisanId: "sunaina-devi",
    artFormId: "madhubani",
    materials: ["Cotton canvas", "Natural pigment"],
    timeRequired: "About 40 days",
    storyBehind:
      "The kohbar is painted on the wall of a wedding chamber. Every element in it — lotus, bamboo, parrot — is part of a marriage blessing rather than a decoration.",
    image: images.madhubani,
  },
  {
    id: "pattachitra-jagannath",
    name: "Jagannath Triad Patta",
    price: "₹18,500",
    priceValue: 18500,
    detail: "Tussar cloth · 24 × 36 in · natural stone colours",
    artisanId: "raghunath-maharana",
    artFormId: "pattachitra",
    materials: ["Layered tussar cloth", "Tamarind seed paste", "Stone and shell colour"],
    timeRequired: "About 7 weeks including cloth preparation",
    storyBehind:
      "Ten days go into the cloth before a line is drawn. Raghunath treats the preparation as the real work and the painting as what follows from it.",
    image: images.pattachitra,
  },
  {
    id: "pattachitra-palm-leaf",
    name: "Krishna Leela Palm Leaf",
    price: "₹5,900",
    priceValue: 5900,
    detail: "Palm leaf etching · 6 × 14 in",
    artisanId: "raghunath-maharana",
    artFormId: "pattachitra",
    materials: ["Cured palm leaf", "Iron stylus", "Lamp black"],
    timeRequired: "About 12 days",
    storyBehind:
      "The lines are cut, not painted — black is rubbed into the incisions afterwards. It is the same technique Odisha used for manuscripts.",
    image: images.pattachitra,
  },
  {
    id: "warli-tarpa",
    name: "Tarpa Dance Circle",
    price: "₹9,200",
    priceValue: 9200,
    detail: "Canvas with cow-dung wash · 30 × 30 in",
    artisanId: "jivya-more",
    artFormId: "warli",
    materials: ["Cotton canvas", "Mud and cow-dung wash", "Rice paste white"],
    timeRequired: "About 3 weeks",
    storyBehind:
      "The dancers spiral around the tarpa player with no start and no end — the way the dance itself works, joined and left as the night goes on.",
    image: images.warli,
  },
  {
    id: "warli-harvest",
    name: "Harvest Village",
    price: "₹4,100",
    priceValue: 4100,
    detail: "Handmade paper · 16 × 20 in",
    artisanId: "jivya-more",
    artFormId: "warli",
    materials: ["Handmade paper", "Rice paste white"],
    timeRequired: "About 8 days",
    storyBehind:
      "A whole agricultural year compressed into one sheet: sowing, threshing, the shared meal, drawn with three shapes.",
    image: images.warli,
  },
  {
    id: "dhokra-horse-rider",
    name: "Bastar Horse Rider",
    price: "₹7,600",
    priceValue: 7600,
    detail: "Bell metal · 9 in · lost-wax cast",
    artisanId: "budhiyarin-bai",
    artFormId: "dhokra",
    materials: ["Beeswax", "River clay", "Bell metal"],
    timeRequired: "About 3 weeks including one firing cycle",
    storyBehind:
      "The surface texture is the wax thread itself, coiled by hand before the metal ever entered the mould. The mould was broken to get this piece out.",
    image: images.dhokra,
  },
  {
    id: "dhokra-bowls",
    name: "Measuring Bowl Set",
    price: "₹5,300",
    priceValue: 5300,
    detail: "Bell metal · set of three",
    artisanId: "budhiyarin-bai",
    artFormId: "dhokra",
    materials: ["Beeswax", "River clay", "Bell metal"],
    timeRequired: "About 2 weeks",
    storyBehind:
      "Measures like these were household objects in Bastar long before they were collected. The proportions are the ones grain was actually sold by.",
    image: images.dhokra,
  },
  {
    id: "bluepottery-vase",
    name: "Cobalt Vine Vase",
    price: "₹4,800",
    priceValue: 4800,
    detail: "Quartz body · 11 in · hand-painted",
    artisanId: "iqbal-khan",
    artFormId: "blue-pottery",
    materials: ["Powdered quartz", "Glass frit and borax", "Cobalt oxide"],
    timeRequired: "About 2 weeks including drying",
    storyBehind:
      "Iqbal grinds his own cobalt rather than buying ready mixed. It is the reason the blue sits deep instead of sitting on top of the glaze.",
    image: images.bluePottery,
  },
  {
    id: "bluepottery-tiles",
    name: "Tile Set of Nine",
    price: "₹6,900",
    priceValue: 6900,
    detail: "4 × 4 in each · glazed",
    artisanId: "iqbal-khan",
    artFormId: "blue-pottery",
    materials: ["Powdered quartz", "Cobalt oxide", "Glass glaze"],
    timeRequired: "About 3 weeks",
    storyBehind:
      "Nine tiles survived from a firing of fourteen. The rest cracked, which is normal for a body that holds no clay.",
    image: images.bluePottery,
  },
  {
    id: "banarasi-kadhwa-saree",
    name: "Kadhwa Silk Saree",
    price: "₹68,000",
    priceValue: 68000,
    detail: "Pure silk · real zari · 6 months on the loom",
    artisanId: "shahid-ansari",
    artFormId: "banarasi",
    materials: ["Mulberry silk", "Real zari"],
    timeRequired: "About 6 months",
    storyBehind:
      "Every motif is woven separately rather than carried across the back of the cloth. It doubles the time and it is why the reverse is clean enough to wear.",
    image: images.banarasi,
  },
  {
    id: "banarasi-stole",
    name: "Brocade Stole",
    price: "₹9,400",
    priceValue: 9400,
    detail: "Silk & zari · 28 × 80 in",
    artisanId: "shahid-ansari",
    artFormId: "banarasi",
    materials: ["Mulberry silk", "Zari"],
    timeRequired: "About 3 weeks",
    storyBehind:
      "Woven between saree commissions on the same jala loom, using the border pattern from a design Shahid's grandfather knotted.",
    image: images.banarasi,
  },
];
