import type { Region } from "./types";

export const regions: Region[] = [
  {
    id: "jammu-kashmir",
    name: "Kashmir",
    x: 45,
    y: 13,
    note: "Persian-influenced surface craft carried over the mountain passes.",
    districts: [{ name: "Srinagar", artFormIds: [] }],
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    x: 40,
    y: 33,
    note: "Court patronage turned desert workshops into pigment laboratories.",
    districts: [{ name: "Jaipur", artFormIds: ["blue-pottery"] }],
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    x: 51,
    y: 32,
    note: "The loom belt of the Gangetic plain.",
    districts: [{ name: "Varanasi", artFormIds: ["banarasi"] }],
  },
  {
    id: "bihar",
    name: "Bihar",
    x: 58,
    y: 38,
    note: "Wall painting by women, done for weddings, now on paper.",
    districts: [{ name: "Madhubani", artFormIds: ["madhubani"] }],
  },
  {
    id: "gujarat",
    name: "Gujarat",
    x: 36,
    y: 45,
    note: "Double-ikat and resist printing older than most nations.",
    districts: [{ name: "Kutch", artFormIds: [] }],
  },
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    x: 47,
    y: 44,
    note: "Forest cosmology drawn in dots and dashes.",
    districts: [{ name: "Dindori", artFormIds: ["gond"] }],
  },
  {
    id: "west-bengal",
    name: "West Bengal",
    x: 63,
    y: 44,
    note: "Story scrolls sung aloud as they are unrolled.",
    districts: [{ name: "Paschim Medinipur", artFormIds: ["patua-scroll"] }],
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    x: 55,
    y: 50,
    note: "Lost-wax metal casting practised for millennia.",
    districts: [{ name: "Bastar", artFormIds: ["dhokra"] }],
  },
  {
    id: "odisha",
    name: "Odisha",
    x: 59,
    y: 54,
    note: "Temple painting bound to the Jagannath calendar.",
    districts: [{ name: "Puri", artFormIds: ["pattachitra"] }],
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    x: 42,
    y: 58,
    note: "Tribal geometry and the imperial silk of the Deccan.",
    districts: [{ name: "Palghar", artFormIds: ["warli"] }],
  },
  {
    id: "telangana",
    name: "Telangana & Andhra",
    x: 50,
    y: 66,
    note: "Narrative painting of the Deccan — scrolls, masks and pen-drawn cloth.",
    districts: [
      { name: "Siddipet (Cheriyal)", artFormIds: ["cheriyal"] },
      { name: "Srikalahasti", artFormIds: ["kalamkari"] },
    ],
  },
  {
    id: "karnataka",
    name: "Karnataka",
    x: 45,
    y: 73,
    note: "Lathe-turned lac work and silver-inlaid Deccan metal.",
    districts: [
      { name: "Ramanagara", artFormIds: ["channapatna"] },
      { name: "Bidar", artFormIds: ["bidri"] },
    ],
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    x: 50,
    y: 82,
    note: "Gesso relief and gold foil under Thanjavur patronage.",
    districts: [{ name: "Thanjavur", artFormIds: ["tanjore"] }],
  },
  {
    id: "kerala",
    name: "Kerala",
    x: 45,
    y: 86,
    note: "Temple murals in five vegetable colours.",
    districts: [{ name: "Thrissur", artFormIds: ["kerala-mural"] }],
  },
  {
    id: "assam",
    name: "Assam & North East",
    x: 71,
    y: 35,
    note: "Golden silk reared nowhere else on earth.",
    districts: [{ name: "Sualkuchi", artFormIds: ["muga-silk"] }],
  },
];
